analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#795c56'
    - '#001f00'
    - '#6ba21a'
    - '#c6ec43'
  brandStrength: 0.5
  lightness: 0.998893574138624
  rhythmicContrast: 0.46369574561482485
  saturation: 0.6612659742066399
cta: {}
layout_spectrum: 0.189189
name: HaydenDavey
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.246621
